baseurl = "/"
languageCode = "pt-br"
title = "Curso-R"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
relativeurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-87272102-1"
pluralizeListTitles = false

[params]
  # General information
  author = "Curso-R"
  description = "Materiais para cursos de R"
  copyright = "Disponível sobre Licença MIT"

  # Repository
  provider = "GitHub"
  repo_url = "https://github.com/curso-r/material"

  version = ""
  logo = "logo-curso-r.png"
  favicon = ""

  permalink = "%>%"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  [params.palette]
      primary = "red"
      accent  = "teal"

    [params.font]
      text = "Ubuntu"
      code = "Ubuntu Mono"


[social]
  twitter = "curso_r"
  github  = "curso-r"
  facebook = "cursodeR"
  email   = "contato@curso-r.com"

[[menu.main]]
  name   = "Instalação"
  url    = "instalacao/"
  weight = 05
  
[[menu.main]]
  name   = "R básico"
  url    = "rbase/"
  weight = 10

[[menu.main]]
  name   = "Pipe"
  url    = "pipe/"
  weight = 15
  
[[menu.main]]
  name   = "Importação"
  url    = "import/"
  weight = 20

[[menu.main]]
  name   = "Manipulação"
  url    = "manip/"
  weight = 25
  
[[menu.main]]
  name   = "Visualizações"
  url    = "ggplot/"
  weight = 30

[[menu.main]]
  name   = "Strings"
  url    = "stringr/"
  weight = 35
  
[[menu.main]]
  name   = "Datas"
  url    = "lubridate/"
  weight = 40
  
[[menu.main]]
  name   = "Fatores"
  url    = "forcats/"
  weight = 45

[[menu.main]]
  name   = "Programação Funcional"
  url    = "purrr/"
  weight = 50

[[menu.main]]
  name   = "Modelagem"
  url    = "modelos/"
  weight = 55
  
[[menu.main]]
  name   = "Shiny"
  url    = "shiny/"
  weight = 60

[[menu.main]]
  name   = "APIs"
  url    = "api/"
  weight = 65

[[menu.main]]
  name   = "Web Scraping"
  url    = "scrape/"
  weight = 70

[blackfriday]
  smartypants  = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
